device: "auto"
train:
  - _target_: src.metrics.MSEMetric
    name: "MSE"
inference:
  - _target_: src.metrics.MSEMetric
    name: "MSE"
  - _target_: src.metrics.ReconstructionMetric
    metric:
      _target_: torchmetrics.image.PeakSignalNoiseRatio
      data_range: 1.0
    device: ${metrics.device}
    name: "PSNR"
  - _target_: src.metrics.ReconstructionMetric
    metric:
      _target_: torchmetrics.image.StructuralSimilarityIndexMeasure
      data_range: 1.0
    device: ${metrics.device}
    name: "SSIM"
